image: node

stages:
    - build
    
build_job:
    stage: build
    before_script:
        - npm install -g @angular/cli
        - npm install --save-dev @angular-devkit/build-angular
    script:
        - ng build
    after_script:
        - echo "Build complete"