image: local_angular

stages:
    - build

build_prd:
    stage: build
    only:
      - master
    script:
        - echo n | npm install --silent
        - ng test --browsers ChromeHeadlessCI --code-coverage=true --watch=false
        - sonar-scanner
        - ng build --prod
        - cd dist/GardenLinkWeb
        - tar cvf archive.tar ./
        - curl $CURL_PARAMS "$BINARIES/prd/web$(/bin/date +"%s").tar"

build_dev:
    stage: build
    only:
      - develop
      - dev
    script:
        - echo n | npm install --silent
#        - ng test --browsers ChromeHeadlessCI --code-coverage=true --watch=false
        - sonar-scanner
        - ng build
        - cd dist/GardenLinkWeb
        - tar cvf archive.tar ./
        - curl $CURL_PARAMS "$BINARIES/dev/web$(/bin/date +"%s").tar"

code_insight:
    stage: build
    except:
      - develop
      - dev
      - master
    script:
        - echo n | npm install --silent
        - ng test --browsers ChromeHeadlessCI --code-coverage=true --watch=false
        - sonar-scanner